### ISSUE TITLE
[BUG] Transform `tape_fn` not available in PennyLane v0.33

### ISSUE THREAD

**Issue by glassnotes** [QSAR-UBC/ionizer#5]
A user has described the issue in [this PL forum post](https://discuss.pennylane.ai/t/the-new-pennylane-v0-33-cannot-support-ionizer/3613).

The Ionizer will need to be updated to support the new transform framework; research must be done first to determine how the fix will interact with older versions of the library.

**Comment by trbromley** [comment]
@glassnotes - please let me or @rmoyard know if you need a hand with the new transforms functionality.

**Comment by glassnotes** [comment]
Thanks @trbromley ! Good to go with the newest release here. Fixes were straightforward, based on how the regular PL transforms were updated :tada:
